# Generated by Django 5.2.15 on 2026-07-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='expected_employee_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
