# Generated by Django 5.2.15 on 2026-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0002_companyregistrationrequest_expected_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='reimbursement_email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
