# Generated by Django 5.2.15 on 2026-07-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0003_companyregistrationrequest_reimbursement_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_receipt_email', models.EmailField(default='receipts@zepex.ai', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
