# Generated by Django 5.2.15 on 2026-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_management', '0004_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistrationrequest',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
