# Generated by Django 5.2.15 on 2026-06-07 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReimbursementEmailConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email_address', models.EmailField(help_text='Company reimbursement email, e.g. expenses@bitloom.com', max_length=254)),
                ('imap_host', models.CharField(help_text='Example: imap.gmail.com', max_length=255)),
                ('imap_port', models.IntegerField(default=993)),
                ('imap_username', models.CharField(max_length=255)),
                ('imap_password', models.CharField(help_text='Use app password, not normal email password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='tenants.company')),
            ],
        ),
    ]
