# Generated by Django 5.2.15 on 2026-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_department_is_active_department_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycategoryrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
