# Generated by Django 5.2.15 on 2026-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_companyrole_userprofile_company_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaldatabaseconfig',
            name='db_engine',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('mssql', 'Microsoft SQL Server'), ('oracle', 'Oracle')], max_length=20),
        ),
    ]
