# Generated by Django 5.2.15 on 2026-06-27 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_databasesynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='auto_currency_conversion',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
