# Generated by Django 5.2.15 on 2026-06-27 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='auto_currency_conversion',
        ),
        migrations.RemoveField(
            model_name='company',
            name='base_currency',
        ),
        migrations.CreateModel(
            name='CompanyFinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_currency_conversion', models.BooleanField(default=True)),
                ('exchange_rate_provider', models.CharField(default='ExchangeRate API', max_length=100)),
                ('allow_manual_exchange_rate', models.BooleanField(default=False)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('rounding_enabled', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('last_exchange_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_companies', to='tenants.currency')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='tenants.company')),
            ],
        ),
    ]
