# Generated by Django 5.2.15 on 2026-06-27 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_remove_company_auto_currency_conversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfinancesettings',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_settings', to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='companyfinancesettings',
            name='exchange_rate_provider',
            field=models.CharField(choices=[('ExchangeRate API', 'ExchangeRate API'), ('Open Exchange Rates', 'Open Exchange Rates'), ('Fixer', 'Fixer')], default='ExchangeRate API', max_length=50),
        ),
    ]
