# Generated by Django 5.2.15 on 2026-06-27 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_alter_companyfinancesettings_base_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfinancesettings',
            name='base_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_finance_settings', to='tenants.currency'),
        ),
        migrations.AlterField(
            model_name='companyfinancesettings',
            name='date_format',
            field=models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20),
        ),
        migrations.AlterField(
            model_name='companyfinancesettings',
            name='exchange_rate_provider',
            field=models.CharField(choices=[('ExchangeRate API', 'ExchangeRate API'), ('Open Exchange Rates', 'Open Exchange Rates'), ('Fixer', 'Fixer')], default='ExchangeRate API', max_length=100),
        ),
    ]
