# Generated by Django 5.2.15 on 2026-06-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_companyfinancesettings_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='auto_approve_if_no_violation',
            field=models.BooleanField(default=True),
        ),
    ]
