# Generated by Django 5.2.15 on 2026-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0016_companypolicy_auto_approve_if_no_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invite_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
