# Generated by Django 5.2.15 on 2026-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0017_userprofile_invite_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='temporary_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
