# Generated by Django 5.2.15 on 2026-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0018_userprofile_force_password_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='inbound_email_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='inbound_forwarding_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reimbursement_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='reimbursement_email_prefix',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
