# Generated by Django 5.2.15 on 2026-07-06 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0019_company_inbound_email_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='tenants.userprofile'),
        ),
    ]
