# Generated by Django 5.2.15 on 2026-07-07 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0020_userprofile_reporting_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePolicyCategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_policy_rules', to='tenants.company')),
                ('company_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='tenants.companyrole')),
            ],
            options={
                'unique_together': {('company', 'company_role', 'category_name')},
            },
        ),
    ]
