# Generated by Django 5.2.15 on 2026-07-07 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0023_populate_default_employee_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policycategoryrule',
            name='company_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_category_rules', to='tenants.companyrole'),
        ),
    ]
