# Generated by Django 5.2.15 on 2026-07-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0024_alter_policycategoryrule_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='policycategoryrule',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='is_unlimited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='policy_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='source_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policycategoryrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
