# Generated by Django 5.2.15 on 2026-07-11 09:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0025_policycategoryrule_ai_confidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocumentImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='policy_documents/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('REVIEW_REQUIRED', 'Review Required'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='UPLOADED', max_length=30)),
                ('extracted_json', models.JSONField(blank=True, default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_document_imports', to='tenants.company')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_document_imports', to='tenants.userprofile')),
            ],
        ),
    ]
