# Generated by Django 5.2.15 on 2026-07-13 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0027_policyversion_policycategoryrule_policy_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycategoryrule',
            options={'ordering': ['company_role__name', 'category_name']},
        ),
        migrations.AlterUniqueTogether(
            name='policycategoryrule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='policyversion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_versions', to='tenants.userprofile'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', False)), fields=('policy_version', 'company_role', 'category_name'), name='unique_rule_per_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', True)), fields=('policy', 'company_role', 'category_name'), name='unique_legacy_policy_rule'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(fields=('policy', 'version_number'), name='unique_policy_version_number'),
        ),
        migrations.AddConstraint(
            model_name='policyversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('policy',), name='unique_active_version_per_policy'),
        ),
    ]
