# Generated by Django 5.2.15 on 2026-07-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0028_alter_policycategoryrule_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_language_code', models.CharField(default='en', max_length=20)),
                ('output_language_name', models.CharField(default='English', max_length=100)),
                ('preserve_original_text', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='tenants.company')),
            ],
        ),
    ]
