# Generated by Django 5.2.15 on 2026-07-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0029_companypreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='policydocumentimport',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='document_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='document_language_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='document_quality',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='output_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='output_language_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='policydocumentimport',
            name='prompt_version',
            field=models.CharField(default='v2.0', max_length=50),
        ),
    ]
