# Generated by Django 5.2.15 on 2026-07-14 10:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0030_policydocumentimport_ai_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyVersionComparison',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comparison_data', models.JSONField(blank=True, default=dict)),
                ('ai_summary', models.JSONField(blank=True, default=dict)),
                ('ai_summary_generated', models.BooleanField(default=False)),
                ('generated_by', models.CharField(blank=True, choices=[('GEMINI', 'Gemini'), ('DETERMINISTIC_FALLBACK', 'Deterministic fallback')], max_length=40, null=True)),
                ('ai_model', models.CharField(blank=True, max_length=100, null=True)),
                ('output_language', models.CharField(default='English', max_length=100)),
                ('output_language_code', models.CharField(default='en', max_length=20)),
                ('include_unchanged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_comparisons', to='tenants.userprofile')),
                ('new_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_new_version', to='tenants.policyversion')),
                ('old_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons_as_old_version', to='tenants.policyversion')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_comparisons', to='tenants.companypolicy')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('old_version', 'new_version', 'include_unchanged', 'output_language_code'), name='unique_policy_version_comparison')],
            },
        ),
    ]
