# Generated by Django 5.2.15 on 2026-07-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0031_policyversioncomparison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='reimbursement_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
