# Generated by Django 5.2.15 on 2026-07-14 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0032_alter_company_reimbursement_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policycategoryrule',
            options={'ordering': ['scope', 'company_role__name', 'category_name']},
        ),
        migrations.RemoveConstraint(
            model_name='policycategoryrule',
            name='unique_rule_per_policy_version',
        ),
        migrations.RemoveConstraint(
            model_name='policycategoryrule',
            name='unique_legacy_policy_rule',
        ),
        migrations.AddField(
            model_name='policycategoryrule',
            name='scope',
            field=models.CharField(choices=[('ALL', 'All Employees'), ('ROLE', 'Specific Role')], default='ROLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='policycategoryrule',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_category_rules', to='tenants.companyrole'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', False), ('scope', 'ROLE')), fields=('policy_version', 'company_role', 'category_name'), name='unique_role_rule_per_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', False), ('scope', 'ALL')), fields=('policy_version', 'category_name'), name='unique_all_rule_per_policy_version'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', True), ('scope', 'ROLE')), fields=('policy', 'company_role', 'category_name'), name='unique_legacy_role_policy_rule'),
        ),
        migrations.AddConstraint(
            model_name='policycategoryrule',
            constraint=models.UniqueConstraint(condition=models.Q(('policy_version__isnull', True), ('scope', 'ALL')), fields=('policy', 'category_name'), name='unique_legacy_all_policy_rule'),
        ),
    ]
