# Generated by Django 5.2.15 on 2026-06-07 11:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_reimbursementemailconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('EMAIL_RECEIPT_RECEIVED', 'Email Receipt Received'), ('AI_PROCESSING_STARTED', 'AI Processing Started'), ('AI_PROCESSED', 'AI Processed'), ('REPORT_SUBMITTED', 'Report Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('ACCOUNTS_REJECTED', 'Accounts Rejected'), ('MARKED_PAID', 'Marked Paid'), ('LINE_ITEM_DELETED', 'Line Item Deleted'), ('POLICY_UPDATED', 'Policy Updated')], max_length=60)),
                ('message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to='tenants.userprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tenants.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
