# Generated by Django 5.2.15 on 2026-06-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('EMAIL_RECEIPT_RECEIVED', 'Email Receipt Received'), ('AI_PROCESSING_STARTED', 'AI Processing Started'), ('AI_PROCESSED', 'AI Processed'), ('REPORT_SUBMITTED', 'Report Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('ACCOUNTS_REJECTED', 'Accounts Rejected'), ('MARKED_PAID', 'Marked Paid'), ('LINE_ITEM_DELETED', 'Line Item Deleted'), ('POLICY_UPDATED', 'Policy Updated'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated')], max_length=60),
        ),
    ]
