# Generated by Django 5.2.15 on 2026-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('RECEIPT_UPLOADED', 'Receipt Uploaded'), ('EMAIL_RECEIPT_RECEIVED', 'Email Receipt Received'), ('AI_PROCESSING_STARTED', 'AI Processing Started'), ('AI_PROCESSED', 'AI Processed'), ('REPORT_SUBMITTED', 'Report Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('ACCOUNTS_REJECTED', 'Accounts Rejected'), ('MARKED_PAID', 'Marked Paid'), ('LINE_ITEM_DELETED', 'Line Item Deleted'), ('POLICY_UPDATED', 'Policy Updated'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_ACTIVATED', 'User Activated'), ('DEPARTMENT_UPDATED', 'Department Updated'), ('DEPARTMENT_DEACTIVATED', 'Department Deactivated'), ('DEPARTMENT_ACTIVATED', 'Department Activated'), ('DEPARTMENT_CREATED', 'Department Created'), ('POLICY_RULE_UPDATED', 'Policy Rule Updated'), ('POLICY_RULE_DEACTIVATED', 'Policy Rule Deactivated'), ('POLICY_RULE_ACTIVATED', 'Policy Rule Activated'), ('POLICY_RULE_DELETED', 'Policy Rule Deleted'), ('COMPANY_DEACTIVATED', 'Company Deactivated'), ('COMPANY_ACTIVATED', 'Company Activated')], max_length=60),
        ),
    ]
