# Generated by Django 5.2.15 on 2026-06-04 07:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_file', models.FileField(upload_to='receipts/%Y/%m/%d/')),
                ('vendor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('AI_PROCESSING', 'AI Processing'), ('AI_PROCESSED', 'AI Processed'), ('POLICY_VIOLATION', 'Policy Violation'), ('PENDING_MANAGER', 'Pending Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='SUBMITTED', max_length=30)),
                ('policy_violation_reason', models.TextField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('accounts_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_receipts', to='tenants.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_receipts', to='tenants.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_receipts', to='tenants.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('is_violating', models.BooleanField(default=False)),
                ('violation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='expenses.expensereceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('MANAGER_APPROVED', 'Manager Approved'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], max_length=30)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to='tenants.userprofile')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='expenses.expensereceipt')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('EMAIL', 'Email'), ('WEB_UPLOAD', 'Web Upload')], max_length=20)),
                ('email_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_submissions', to='tenants.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_submissions', to='tenants.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expensesubmission'),
        ),
    ]
