# Generated by Django 5.2.15 on 2026-06-04 08:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensereceipt',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='has_amount_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='has_any_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='has_duplicate_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='has_old_bill_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('ACCOUNTS_REJECTED', 'Accounts Rejected'), ('PAID', 'Paid')], max_length=40),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='expenses.expensereceipt'),
        ),
        migrations.AlterField(
            model_name='expensereceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AI_PROCESSING', 'AI Processing'), ('AI_PROCESSED', 'AI Processed'), ('VALID', 'Valid'), ('POLICY_VIOLATION', 'Policy Violation'), ('SUBMITTED_TO_MANAGER', 'Submitted To Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=40),
        ),
        migrations.CreateModel(
            name='ExpenseReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=30)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('manager_action_at', models.DateTimeField(blank=True, null=True)),
                ('accounts_action_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True, null=True)),
                ('accounts_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='tenants.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_reports', to='tenants.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_reports', to='tenants.userprofile')),
            ],
            options={
                'ordering': ['-month', '-created_at'],
                'unique_together': {('company', 'employee', 'month')},
            },
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='expenses.expensereport'),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expenses.expensereport'),
        ),
        migrations.AddField(
            model_name='expensesubmission',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='expenses.expensereport'),
        ),
    ]
