# Generated by Django 5.2.15 on 2026-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expensereceipt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AI_PROCESSING', 'AI Processing'), ('AI_PROCESSED', 'AI Processed'), ('VALID', 'Valid'), ('POLICY_VIOLATION', 'Policy Violation'), ('SUBMITTED_TO_MANAGER', 'Submitted To Manager'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_COMPANY_ADMIN', 'Pending Company Admin'), ('COMPANY_ADMIN_APPROVED', 'Company Admin Approved'), ('COMPANY_ADMIN_REJECTED', 'Company Admin Rejected'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_COMPANY_ADMIN', 'Pending Company Admin'), ('COMPANY_ADMIN_APPROVED', 'Company Admin Approved'), ('COMPANY_ADMIN_REJECTED', 'Company Admin Rejected'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=30),
        ),
    ]
