# Generated by Django 5.2.15 on 2026-06-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensereceipt_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='company_admin_action_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='company_admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
