# Generated by Django 5.2.15 on 2026-06-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensereport_company_admin_action_at_and_more'),
        ('tenants', '0008_companyrole_userprofile_company_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='workflow_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('MANAGER_APPROVED', 'Manager Approved'), ('MANAGER_REJECTED', 'Manager Rejected'), ('PENDING_COMPANY_ADMIN', 'Pending Company Admin'), ('COMPANY_ADMIN_APPROVED', 'Company Admin Approved'), ('COMPANY_ADMIN_REJECTED', 'Company Admin Rejected'), ('PENDING_ACCOUNTS', 'Pending Accounts'), ('ACCOUNTS_APPROVED', 'Accounts Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=40),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Workflow', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='tenants.company')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('routing_type', models.CharField(choices=[('DEPARTMENT', 'Department Based'), ('COMPANY', 'Company Wide')], default='COMPANY', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='tenants.companyrole')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='expenses.approvalworkflow')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
        migrations.AddField(
            model_name='expensereport',
            name='current_workflow_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_reports', to='expenses.approvalworkflowstep'),
        ),
    ]
