# Generated by Django 5.2.15 on 2026-06-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_expensereport_workflow_completed_and_more'),
        ('tenants', '0008_companyrole_userprofile_company_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensereport',
            old_name='accounts_notes',
            new_name='paid_notes',
        ),
        migrations.RemoveField(
            model_name='expensereceipt',
            name='accounts_notes',
        ),
        migrations.RemoveField(
            model_name='expensereceipt',
            name='manager_notes',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='accounts_action_at',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='company_admin_action_at',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='company_admin_notes',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='manager_action_at',
        ),
        migrations.RemoveField(
            model_name='expensereport',
            name='manager_notes',
        ),
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_steps', to='tenants.department'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('REPORT_SUBMITTED', 'Report Submitted'), ('STEP_APPROVED', 'Step Approved'), ('STEP_REJECTED', 'Step Rejected'), ('PAID', 'Paid')], max_length=40),
        ),
        migrations.AlterField(
            model_name='expensereceipt',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AI_PROCESSING', 'AI Processing'), ('AI_PROCESSED', 'AI Processed'), ('VALID', 'Valid'), ('POLICY_VIOLATION', 'Policy Violation'), ('PENDING_APPROVAL', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='expensereport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PAID', 'Paid')], default='DRAFT', max_length=40),
        ),
    ]
