# Generated by Django 5.2.15 on 2026-06-18 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_rename_accounts_notes_expensereport_paid_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateReceiptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duplicate_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_logs', to='expenses.expensereceipt')),
                ('original_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_duplicate_logs', to='expenses.expensereceipt')),
            ],
        ),
    ]
