# Generated by Django 5.2.15 on 2026-06-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_duplicatereceiptlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='duplicatereceiptlog',
            name='duplicate_type',
            field=models.CharField(choices=[('SAME_EMPLOYEE', 'Same Employee'), ('CROSS_EMPLOYEE', 'Cross Employee')], default='SAME_EMPLOYEE', max_length=30),
        ),
    ]
