# Generated by Django 5.2.15 on 2026-06-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_duplicatereceiptlog_duplicate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='converted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='converted_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='exchange_rate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='exchange_rate_provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='original_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
