# Generated by Django 5.2.15 on 2026-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_expensereceipt_converted_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensereceipt',
            old_name='converted_amount',
            new_name='company_amount',
        ),
        migrations.RenameField(
            model_name='expensereceipt',
            old_name='converted_currency',
            new_name='company_currency',
        ),
        migrations.AlterField(
            model_name='expensereceipt',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='expensereceipt',
            name='exchange_rate_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
