# Generated by Django 5.2.15 on 2026-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_rename_converted_amount_expensereceipt_company_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='auto_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereport',
            name='is_auto_approved',
            field=models.BooleanField(default=False),
        ),
    ]
