# Generated by Django 5.2.15 on 2026-07-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_expensereport_auto_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='ai_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='ai_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='ai_status',
            field=models.CharField(choices=[('AI_PENDING', 'AI Pending'), ('AI_PROCESSING', 'AI Processing'), ('AI_COMPLETED', 'AI Completed'), ('AI_RETRY_REQUIRED', 'AI Retry Required'), ('AI_FAILED', 'AI Failed')], default='AI_PENDING', max_length=40),
        ),
    ]
