# Generated by Django 5.2.15 on 2026-07-06 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_expensereceipt_ai_error_message_and_more'),
        ('tenants', '0019_company_inbound_email_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflow',
            name='start_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='starting_workflows', to='tenants.companyrole'),
        ),
    ]
