# Generated by Django 5.2.15 on 2026-07-06 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_approvalworkflow_start_role'),
        ('tenants', '0020_userprofile_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='approver_type',
            field=models.CharField(choices=[('REPORTING_MANAGER', 'Reporting Manager'), ('DEPARTMENT_MANAGER', 'Department Manager'), ('COMPANY_ROLE', 'Company Role'), ('SPECIFIC_USER', 'Specific User')], default='COMPANY_ROLE', max_length=30),
        ),
        migrations.AddField(
            model_name='approvalworkflowstep',
            name='specific_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specific_workflow_steps', to='tenants.userprofile'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='tenants.company'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='name',
            field=models.CharField(default='Workflow', max_length=100),
        ),
        migrations.AlterField(
            model_name='approvalworkflowstep',
            name='approver_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to='tenants.companyrole'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('company', 'start_role')},
        ),
    ]
