# Generated by Django 5.2.15 on 2026-07-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_approvalworkflowstep_approver_type_and_more'),
        ('tenants', '0020_userprofile_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_expense_reports', to='tenants.userprofile'),
        ),
    ]
