# Generated by Django 5.2.15 on 2026-07-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_expensereport_current_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenselineitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
