# Generated by Django 5.2.15 on 2026-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_alter_expenselineitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereceipt',
            name='ai_extracted_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='original_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='original_language_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='output_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expensereceipt',
            name='output_language_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
